.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, CONTRIBUTING.md
Ajout du fichier de contribution et des modèles pour les issues Features et Bugs
=> chore: add contributing notice and issues templates

src/3.1_b.js, src/3.2.1_mur.js, src/3.3_baie_vitree.js, src/5_conso_ventilation.js, src/constants.js
Correction du ticket https://github.com/jzck/Open3CL/issues/13
=> fix(issue-13): cast value before compare

.eslintrc.json, jest.config.js, package-lock.json, package.json, src/core/assets/domain/synchronize-assets.spec.js, src/core/assets/domain/synchronize-c1-tables.spec.js, src/core/assets/domain/synchronize-enum-tables.js, src/core/assets/domain/synchronize-enum-tables.spec.js, src/core/assets/domain/synchronize-solicitations-tables.js, src/core/assets/domain/synchronize-solicitations-tables.spec.js, src/core/assets/domain/synchronize-valeur-tables.js, src/core/assets/domain/synchronize-valeur-tables.spec.js, src/core/file/infrastructure/adapter/file.store.js, src/core/file/infrastructure/adapter/file.store.spec.js, src/core/util/infrastructure/object-util.spec.js, test/fixtures/core/assets/c1-tables.fixture.js, test/fixtures/core/assets/enum-tables.fixture.js, test/fixtures/core/assets/solicitations-tables.fixture.js, test/fixtures/core/assets/valeur-tables.fixture.js, test/setup-jest.js
- Ajout de tests unitaires sur les fichiers js de synchronisation que j'ai poussé avant
- Il manquait la lib `@semantic-release/git` dans le package.json
=> test: add sycnhronizations unit tests

index.js, src/index.js
Ajout de fichier d'index manquant et nécessaire pour pouvoir importer la lib
=> fix: add missing index files

package.json
Set package to public to be able to publish to npm registry
=> ci: set package public

src/3.2.1_mur.js, src/3.2.1_mur.spec.js
Close #27 
@jzck , je pense qu'il y a une erreur dans le choix de prendre ou pas la date de construction comme date d'isolation.
Dans mon cas de figure j'ai la date d'isolation qui est renseignée et elle est remplacée par la date de construction alors qu'elle ne devrait pas il me semble.
=> fix: bad value if isolation construction date is known

package.json, src/3.3_baie_vitree.js, src/3.3_baie_vitree.spec.js
=> fix(issue-33): search with correct precision into tv

test/open3cl-sorties-sortie-par-energie.spec.js, test/open3cl-sorties.spec.js, test/open3cl.spec.js
Des tests sont en échec car je compare des valeurs numérique à la place des lettres, de plus, certaines valeurs sont absentes sans pour autant être une erreur.
=> chore: fix tests with non numerics values

src/3.2.2_plancher_bas.js, src/3.2.2_plancher_bas.spec.js
=> fix(issue-44): bad upb in plancher bas deperdition when isolation date is known

src/3.2.3_plancher_haut.js, test/open3cl_tv.spec.js
=> fix: #issue 48 - saisie manuelle uph

src/2021_04_13_qualite_isolation.js, src/7_inertie.js, test/fixtures/2421E0125604W.xml, test/open3cl_tv.spec.js
Close https://github.com/jzck/Open3CL/issues/50
=> fix(issue-50): process a dpe with empty plancher_bas_collection

src/3.4_pont_thermique.js
Prise en compte des ponts thermiques pour les fenêtres ou les portes référencés dans le DPE
Close https://github.com/jzck/Open3CL/issues/52
=> fix(issue-52): process a dpe with pont_thermique other than mur type

src/3.4_pont_thermique.js, test/open3cl-sorties-deperdition.spec.js
Close https://github.com/jzck/Open3CL/issues/56
=> Dpe avec ponts thermique pour un plancher bas sur terre plein

src/3.4_pont_thermique.js, test/open3cl-sorties-deperdition.spec.js
Close https://github.com/jzck/Open3CL/issues/58
=> fix(issue-58): process a dpe with pont_thermique for "plancher bas" and periode_isolation

src/3.2.1_mur.js, src/3.2.3_plancher_haut.js, test/open3cl_misc.spec.js
=> fix: #issue 67 - invalide tv_umur_id if no periode_isolation

src/3.2.2_plancher_bas.js, src/3.2.3_plancher_haut.js, test/open3cl_misc.spec.js
=> fix: #81 - upb0 and uph0 are missing id methode_saisi=9

src/3.2.2_plancher_bas.js, src/3.2.3_plancher_haut.js, src/3.3_baie_vitree.js, src/6.2_surface_sud_equivalente.js, src/7_inertie.js, src/apport_et_besoin.js, src/conso.js, src/engine.js
@jzck J'ai fait un revert de la PR #86 car cela créeait des null pointeur exception (à cause des `toString()`)
Du coup je recrée une pr avec juste un fix sur les égalités `===` plutot que `==`
=> fix: force strict comparison

src/3.4_pont_thermique.js
Close https://github.com/jzck/Open3CL/issues/100
=> fix(issue-100): Use ite as isolation type when isolation_plancher === 'isolé mais type d\'isolation inconnu'

src/9_besoin_ch.js
Close https://github.com/jzck/Open3CL/issues/104
=> fix(issue-104): With several ECS, get take them all into account when calculating losses

src/3.2.1_mur.js, src/7_inertie.js, src/7_inertie.spec.js, src/engine.js, src/utils.js, src/utils.spec.js, test/open3cl-inertie.spec.js
Close https://github.com/jzck/Open3CL/issues/106
=> fix(feat-106): fix inertie calculation

src/13.2_generateur_combustion_ch.js
Close https://github.com/jzck/Open3CL/issues/108
=> fix(feat-108): use the load threshold in decimal

src/14_generateur_ecs.js, src/9_generateur_ch.js
Close https://github.com/jzck/Open3CL/issues/117
=> fix(feat-117): Fix rendement for generateur PAC

src/14_generateur_ecs.js, src/9_besoin_ch.js
Close https://github.com/jzck/Open3CL/issues/119
Close https://github.com/jzck/Open3CL/issues/121
=> fix(feat-119): Fix pertes distribution ecs recup

src/11_besoin_ecs.js, src/11_nadeq.js, src/11_nadeq.spec.js, src/apport_et_besoin.js, src/engine.js, test/open3cl-nadeq.spec.js
Close https://github.com/jzck/Open3CL/issues/122
=> fix(feat-122): Fix nadeq calculation and add unit tests

src/3.2.2_plancher_bas.js, src/3.2.3_plancher_haut.js
Close https://github.com/jzck/Open3CL/issues/126
=> fix(feat-126): Fix undefined periode_isolation_id

src/3.4_pont_thermique.js, src/3_deperdition.js, src/engine.js
Close https://github.com/jzck/Open3CL/issues/129
=> fix(fix-129): Library should not stop calculation if data is not correctly set

src/11_ecs.js, src/14_generateur_ecs.js, src/engine.js
Close https://github.com/jzck/Open3CL/issues/125
=> fix(fix-125): ECS generation with solar production

src/11_besoin_ecs.js, src/11_ecs.js, src/12.4_pac.js, src/13.2_generateur_combustion.js, src/14_generateur_ecs.js, src/apport_et_besoin.js, src/conso.js, src/engine.js
Close https://github.com/jzck/Open3CL/issues/124
Close https://github.com/jzck/Open3CL/issues/131
Close https://github.com/jzck/Open3CL/issues/133
Close https://github.com/jzck/Open3CL/issues/136
=> feat: Virtualization or proration of ECS needs

src/11_besoin_ecs.js, src/11_ecs.js, src/12.4_pac.js, src/13.2_generateur_combustion.js, src/14_generateur_ecs.js, src/3_deperdition.js, src/4_ventilation.js, src/apport_et_besoin.js, src/conso.js, src/engine.js
Close https://github.com/jzck/Open3CL/issues/137
=> Ventilation deperdition

src/14_generateur_ecs.js, src/9_besoin_ch.js, src/apport_et_besoin.js, src/engine.js, src/utils.js
Close https://github.com/jzck/Open3CL/issues/144
Close https://github.com/jzck/Open3CL/issues/145
=> fix(fix-145/fix-144): ECS recup and volume stockage

src/13.2_generateur_combustion.js, src/13.2_generateur_combustion_ch.js, src/4_ventilation.js, src/9_besoin_ch.js, src/9_chauffage.js, src/9_conso_ch.js, src/9_emetteur_ch.js, src/9_generateur_ch.js, src/conso.js, src/engine.js, src/ficheTechnique.js, test/constant.js, test/open3cl-inertie.spec.js, test/open3cl-sorties-apport-besoin.spec.js, test/open3cl-sorties-deperdition.spec.js, test/open3cl-sorties.spec.js
Close https://github.com/jzck/Open3CL/issues/157
=> fix(fix-157): hperm calculation with plusieurs_facade_exposee

src/3.4_pont_thermique.js, src/9_generateur_ch.js, src/engine.js
Note : j'ai enlevé le TODO dans refend / mur car je pense que c'est traité ? 
```javascript
// ligne 46
case 'refend / mur':
list_2 = null;
break;
..
```
=> feat: Add some logs

src/engine.js
Close https://github.com/jzck/Open3CL/issues/97
=> fix(fix-97): Inertie should not be changed, log an error if calculated inertie is different

src/14_generateur_ecs.js, src/3.1_b.js, src/3.2.1_mur.js, src/3.3_baie_vitree.js, src/3.4_pont_thermique.js, src/3_deperdition.js, src/utils.js
- Calcul de b en tuilisant aiu et aue
- Récupération du type de doublage dans la description
- Récupération de Ujn saisi
- Type de générateur 'accumulateur gpl/propane/butane'
- bug_for_bug_compat pour presence_retour_isolation qui n'est pas toujours utilisé de la même manière
=> Fix deperditions

src/14_generateur_ecs.js
Close https://github.com/jzck/Open3CL/issues/176
=> fix(fix-176): Take the fecs_saisi field if present

src/3.2.3_plancher_haut.js
Close https://github.com/jzck/Open3CL/issues/178
=> fix(fix-178): Checking the correct value for type_toiture

src/3.4_pont_thermique.js
Close https://github.com/jzck/Open3CL/issues/152
=> fix(fix-152): Fix Pont thermique calculation

src/9_besoin_ch.js, src/engine.js, src/ficheTechnique.js
Close https://github.com/jzck/Open3CL/issues/180
=> fix(fix-180): No stockage ECS recup when stockage is not in heated volume

src/conso.js
- Correction de la comparaison de type d'énergie par id.
- Pour l'electricité, il faut différencier le coefficient en fonction de chauffage, ecs et autres
- Ajout de valeurs manquantes dans le tableau
=> fix: Fix calcul sortie_par_energie pour elec

src/3.2.1_mur.js
Close https://github.com/jzck/Open3CL/issues/191
=> fix(fix-191): Fix Umu calculation when isolation is unknown

src/3.4_pont_thermique.js
Close https://github.com/jzck/Open3CL/issues/194
=> fix(fix-152): Fix Pont thermique calculation for mur bois

src/14_generateur_ecs.js
Close https://github.com/jzck/Open3CL/issues/198
=> fix(fix-198): Scop or Cop can be specified directly

src/engine.js
Close https://github.com/jzck/Open3CL/issues/202
=> fix(fix-202): Use the type of heating for ECS if mixed generation and wrong ECS generator

src/3.4_pont_thermique.js, src/3_deperdition.js, src/engine.js
Close https://github.com/jzck/Open3CL/issues/205
Close https://github.com/jzck/Open3CL/issues/206
Close https://github.com/jzck/Open3CL/issues/207
=> fix(fix-205/206/207): Fix Pont thermique calculation

src/13.2_generateur_combustion.js, src/13.2_generateur_combustion_ch.js, src/14_generateur_ecs.js, src/engine.js, src/ficheTechnique.js
Close https://github.com/jzck/Open3CL/issues/173
=> fix(fix-173): Implements 'Poele à bois bouilleur' generator

src/9_besoin_ch.js
Ex: 2478E3201212R
installation elec + installation combustion
=> fix: pertes chauffage recup avec double installation

src/11_ecs.js, src/13.2_generateur_combustion.js, src/13.2_generateur_combustion_ch.js, src/14_generateur_ecs.js, src/9_chauffage.js, src/9_generateur_ch.js, src/engine.js
Suppression de l'utilisation de la variable global. Les données sont passées aux fonctions
=> fix: Remove usage of global

src/3.3_baie_vitree.js
fix https://github.com/jzck/Open3CL/issues/219
=> fix(fix-219): Add sw and uw for double_fenetre

src/3.4_pont_thermique.js
fix https://github.com/jzck/Open3CL/issues/227
=> fix(fix-227): Fix pont thermique calculation for adjacence "Hall"

scripts/synchronize_assets.js, src/10_besoin_fr.js, src/11_besoin_ecs.js, src/3.2.2_plancher_bas.js, src/apport_et_besoin.js, src/core/assets/domain/add-additionnal-ue-values-tables.js, src/core/assets/domain/synchronize-valeur-tables.js, src/core/assets/domain/synchronize-valeur-tables.spec.js, src/core/tv/infrastructure/assets/additional-ue-values.js, src/tv.js
fix https://github.com/jzck/Open3CL/issues/225
=> fix(fix-225): Fix calculation for deperdition_plancher_bas

src/conso.js
fix https://github.com/jzck/Open3CL/issues/232
=> fix(fix-232): Add missing GES coefficient for GPL

src/conso.js
fix https://github.com/jzck/Open3CL/issues/235
=> fix(fix-235): Missing enum_type_energie_id when calculating conso

src/10_clim.js, src/12.4_pac.js, src/13.2_generateur_combustion.js, src/13.2_generateur_combustion_ch.js, src/14_generateur_ecs.js, src/9_generateur_ch.js
fix https://github.com/jzck/Open3CL/issues/244
=> fix(fix-244): Use enum_methode_saisie_carac_sys_id to know if the data should be calculated

src/15_conso_aux.js, src/9_chauffage.js, src/9_generateur_ch.js, src/conso.js, src/engine.js
https://github.com/jzck/Open3CL/issues/250
=> feat(feat-250): Add auxiliaire_distribution_ch for ch with circulator

src/14_generateur_ecs.js
fix https://github.com/jzck/Open3CL/issues/253
=> fix(fix-253): Fix of conso_ecs calculation for default generator

src/6.2_surface_sud_equivalente.js
https://github.com/jzck/Open3CL/issues/215
=> fix: Add verandas for surface_sud_equivalente calculation

src/15_conso_aux.js, src/9_chauffage.js, src/9_generateur_ch.js
Quelques fixs suite à https://github.com/jzck/Open3CL/issues/250
=> fix(fix-250): Add auxiliaire_distribution_ch for ch with circulator

src/14_generateur_ecs.js
fix https://github.com/jzck/Open3CL/issues/262
=> fix(fix-262): Qp0 should be calculated for generateur 'accumulateur gaz'

src/3.3_baie_vitree.js
fix https://github.com/jzck/Open3CL/issues/270
=> fix(fix-270): Fix sw for baie_vitree with material 'brique de verre' or 'polycarbonate'

src/utils.js
fix https://github.com/jzck/Open3CL/issues/268
=> fix(fix-268): Fix tv match for condition with ≥ or ≤ characters

src/9_chauffage.js
fix https://github.com/jzck/Open3CL/issues/274
=> fix(fix-274): Conso CH for multiple combustion generators

src/6.2_surface_sud_equivalente.js
fix https://github.com/jzck/Open3CL/issues/280
=> fix(fix-280): Fix fe2 for baie_vitree with multiple masque_lointain_non_homogene

src/9_chauffage.js
https://github.com/jzck/Open3CL/issues/289
=> fix(fix-289): Fix conso_ch with several generator in cascade for same emetteur

src/3.3_baie_vitree.js
fix https://github.com/jzck/Open3CL/issues/291
=> fix(fix-291): Fix sw for polycarbonate baie_vitree

src/14_generateur_ecs.js
fix https://github.com/jzck/Open3CL/issues/143
=> fix(fix-143): Conso ECS for 'installation collective multi-bâtiment'

src/16_conso_eclairage.js, src/6.2_surface_sud_equivalente.js, src/9_conso_ch.js, src/conso.js, test/fixtures/2213E2971717J.xml
fix https://github.com/jzck/Open3CL/issues/304
=> fix(fix-304): Use cle_repartition_ventilation and cle_repartition_ch for conso_auxiliaire

src/10_clim.js
https://github.com/jzck/Open3CL/issues/307
=> fix(fix-307): Get eer from donnee_intermediaire when enum_methode_saisie_carac_sys_id = 6,7,8

src/3.2.2_plancher_bas.js
Upb_saisi doit toujours être prioritaire
=> fix: upb_saisi must take priority over epaisseur_isolation and resistance_isolation

src/9_chauffage.js, src/9_conso_ch.js
fix https://github.com/jzck/Open3CL/issues/311
=> fix(fix-311): Proration of ch needs for multiple installation of ch
